version: '3.9'
services:
  redis:
    container_name: assets-redis
    image: redis:6.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis

  celery:
    build: .
    container_name: assets-celery
    command: celery -A assetsproject worker --loglevel=INFO -n worker1_default@%h -Q 'default'
    volumes:
      - .:/code
    depends_on:
      - redis

  celery_beat:
    build: .
    container_name: assets-celery-beat
    command: celery -A assetsproject beat --loglevel=DEBUG
    volumes:
      - .:/code
    depends_on:
      - redis

  db:
    container_name: assets-db
    image: library/postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/11/data

  web:
    container_name: assets-web
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    env_file: .env
    environment:
        - DATABASE_HOST=assets-db
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USER=${DATABASE_USER}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
      - redis
      - celery
      - celery_beat

volumes:
  redis-data:
  db-data: