# Generated by Django 4.2.20 on 2025-06-23 13:42

import assets.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('upper_limit', models.DecimalField(decimal_places=2, max_digits=10, validators=[assets.validators.GreaterThanValueValidator(0)], verbose_name='Limite superior')),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=10, validators=[assets.validators.GreaterThanValueValidator(0)], verbose_name='Limite inferior')),
                ('tracking_frequency', models.PositiveSmallIntegerField(verbose_name='Frequência de monitoramento (em minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAmountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[assets.validators.GreaterThanValueValidator(0)], verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_history', to='assets.asset', verbose_name='Ativo')),
            ],
        ),
    ]
